name: couldai_user_app
description: "A modern Android SSH client with integrated tools."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # UI & State
  provider: ^6.1.1
  google_fonts: ^6.1.0
  intl: ^0.19.0
  
  # Terminal & SSH
  xterm: ^3.2.6
  dartssh2: ^2.10.0
  
  # System & Hardware
  battery_plus: ^6.0.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  file_picker: ^8.0.0
  
  # Security & Crypto
  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.3
  
  # Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
